---
color: "#23272A"
defaults:
  -
    values:
      layout: default
image: /src/favicon/icon.jpg
name: Discord Utils
permalink: pretty
sass:
  style: compressed
twitter: "@xDimGG"
url: "https://utils.dim.codes"